controllers:
    resource: ../../src/Controller/
    type: annotation

client_index:
    path: "/redirect/index"
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://jeemail.com"
        permanent: true

client_login:
    path: "/redirect/login"
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: "https://jeemail.com/login"
        permanent: true
